openapi: 3.0.0
info:
  title: AI Chatbot API
  version: 1.0.0
  description: API for AI chatbot functionality in the Todo application
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  /api/{user_id}/chat:
    post:
      summary: Process chat message and return AI response
      description: Handles user chat input, processes it through the AI agent, and returns the response
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user sending the message
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The user's chat message
                  example: "Add a task to buy groceries"
                conversation_id:
                  type: integer
                  description: Optional ID of existing conversation to continue
                  example: 123
              required:
                - message
      responses:
        '200':
          description: Successful response from the AI chatbot
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: integer
                    description: ID of the conversation (new or existing)
                    example: 123
                  message:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: ID of the assistant's response message
                        example: 456
                      role:
                        type: string
                        enum: [assistant]
                        description: Role of the message sender
                      content:
                        type: string
                        description: The AI's response content
                        example: "I've added the task 'buy groceries' to your list."
                      created_at:
                        type: string
                        format: date-time
                        description: Timestamp when the message was created
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the tool that was called
                          example: "add_task"
                        parameters:
                          type: object
                          description: Parameters passed to the tool
                        result:
                          type: object
                          description: Result returned by the tool
                  task_operations:
                    type: array
                    items:
                      type: object
                      properties:
                        operation:
                          type: string
                          description: The operation that was performed
                          example: "task_added"
                        task_id:
                          type: integer
                          description: ID of the affected task
                          example: 789
                        task_details:
                          type: object
                          description: Details about the affected task
        '400':
          description: Bad request - invalid input
        '401':
          description: Unauthorized - invalid or missing authentication
        '403':
          description: Forbidden - user trying to access another user's resources
        '500':
          description: Internal server error
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT